### ISSUE TITLE
Java version updated

### ISSUE THREAD

**Issue by agonist** [wisdom-framework/wisdom-docker#2]
Hi, recently Docker made some changes included Java. As you can see in this post images has moved http://blog.docker.com/2015/03/updates-available-to-popular-repos-update-your-images/

I had the same issue : https://forums.aws.amazon.com/thread.jspa?messageID=621752

You can find all java version here https://registry.hub.docker.com/_/java/  but it seem that it use only openJDK for the moment.

**Comment by cescoffier** [comment]
Yes, Docker has made disrupting changes, and so far I didn't take time to update. I need to find a base image including Oracle JVM (as it's the one we used so far).

**Comment by agonist** [comment]
Since I've update my docker file, my application doesn't works anymore (well the wisdom monitoring still working). Do you think it can be related by the fact the new java version used by Docker come from OpenJDK ?

I have again JavaFX error in my deployed version with Docker (in local I don't have any error)

in my Dockerfile I replaced the old Java version by : FROM java:8u45-jre

```
08:32:30.287 [[iPOJO] pool-1-thread-1] ERROR o.o.util.log.impl.osgi.LoggerService - [ERROR]  : [wisdom:jcrom:crudservice:provider] The callback method start has thrown an exception : javafx/beans/property/ListProperty
java.lang.NoClassDefFoundError: javafx/beans/property/ListProperty
```

It's probably not a Wisdom issue, but do you think the java version used by Docker can be gulty ?

**Comment by cescoffier** [comment]
It's not a wisdom issue, it's a wisdom-jcr dependency on javafx (don't ask
me why).
OpenJDK does not have javafx.

2015-05-12 11:03 GMT+02:00 Bastien notifications@github.com:

**Comment by agonist** [comment]
http://stackoverflow.com/questions/18547362/javafx-and-openjdk/19529820#19529820 OpenJDK have JavaFX. 

But the javafx issue come from our jcrom fork. (but it worked before the docker update, if you remember you have given me a chameleon.properties to avoid javafx problems like this one)

I continue to look for what can be wrong...

**Comment by cescoffier** [comment]
I'm on it. Switching to open jdk, also relocating the image to look more 'official;
